### ISSUE TITLE
confirm moderator commands

### ISSUE THREAD

**Issue by derselbst** [chuck-norris-network/teeworlds#12]
to clarify moderator privileges:
* I can `set_team` but I cant `shuffle_team`, intended?
* It seems like i can force `vote yes`, but `force_vote` directly will fail for ?all? commands due to changing the underlying settings (`sv_map`, `sv_teamdamage`, ...) is denied

**Comment by black-roland** [comment]
> I can set_team but I cant shuffle_team, intended?

Yes. But you can vote for "Shuffle teams" option and force it with `vote yes`.

> It seems like i can force vote yes, but force_vote directly will fail for ?all? commands due to changing the underlying settings (sv_map, sv_teamdamage, ...) is denied

This button is the only one reason why `force_vote` enabled :) You can ban or move to spectators using client interface.

![screenshot_2016-12-06_17-23-12](https://cloud.githubusercontent.com/assets/1756198/20918174/6549e3ce-bbe1-11e6-9815-f276a22de171.png)

**Comment by black-roland** [comment]
Admin privileges dropped because it results in configuration inconsistency. Current server setup has its reasons and time-tested. Also changing of settings in runtime is pointless, because after restart everything will go back to the initial setup.

**Comment by derselbst** [comment]
> Yes. But you can vote for "Shuffle teams" option and force it with vote yes.

This indirect approach confused me, wasnt sure whether this was intended at all.

> This button is the only one reason why force_vote enabled

...makes sense, ok :)
