### ISSUE TITLE
let authed spectators allow starting a vote

### ISSUE THREAD

**Issue by derselbst** [chuck-norris-network/teeworlds#17]
on occasion, please change https://github.com/chuck-norris-network/teeworlds/blob/0.6/src/game/server/gamecontext.cpp#L671 to:

if(pPlayer->GetTeam() == TEAM_SPECTATORS && !Server()->IsAuthed(ClientID))

**Comment by black-roland** [comment]
My builder virtual machine broken now. I'll try to fix it ASAP and deploy changes.

**Comment by black-roland** [comment]
Done. I wait till all leave so I can restart servers.
