### ISSUE TITLE
Fix VS2010 Compilers Errors

### ISSUE THREAD

**Issue by MyNewBie** [chuck-norris-network/teeworlds#19]
I cant compile source with VS2010. I can share errors if needed.

**Comment by derselbst** [comment]
you realized that this is the chuck-norris fork? your issues seem to be rather general. please report them to [teeworlds upstream repo](https://github.com/teeworlds/teeworlds)

**Comment by derselbst** [comment]
btw, we are on linux. for us, this is no issue. also, there is nothing interesting to see here, since there are no client side mods. so, unless you dont submit a patch, this probably wont fix, sry.
