### ISSUE TITLE
really ban cheaters?

### ISSUE THREAD

**Issue by derselbst** [chuck-norris-network/teeworlds#2]
Just saw that you prefer banning player. Are you sure? Imagine:

Setting their health to 1, will allow them to stay in the game, while having a great handicap since every newbie will be able to kill the cheater instantly. That's annoying. So the cheater will probably reconnect to the server and find: "Oh no, still 1 hp, well, not worth playing, go off / go to another server."

If you ban people instead, you somewhat offer them a challenge; they want to come back. And despite the ban by /24 subnet (which you guys are using, right?) some people are very successful in making it back to the game.

Also: There may be a very few cases where cheats like autohook are actually intended, e.g. if some guys meet up for doing some hook-fly. Banning them would be pretty rude.

**Comment by black-roland** [comment]
> If you ban people instead, you somewhat offer them a challenge; they want to come back. And despite the ban by /24 subnet (which you guys are using, right?) some people are very successful in making it back to the game.

When player enters again it [matches using name/clan/ip](https://github.com/chuck-norris-network/teeworlds/blob/5712e3f2c14d6c13d20034078fd6c3cc8c274f1d/src/game/server/rcd.cpp#L53). If one of this parameters matches warning level for this player is set = 0.5 \* rcd_max_warnings. So  cheater will be banned 2 times faster. I also keep a track of the latest bans and ban by /24 subnet on on all servers.

**Comment by derselbst** [comment]
> When player enters again it matches using name/clan/ip.

And that's a problem IMO. The IP test is strong and definite, while checking for name+clan is only kindergarden. If a guy is skilled enough to get a new ip, he'll soon comprehend that name+clan check, allowing to bypass it. Furthermore, if they realize, that they just have to disconnect and reconnect again, after playing for a few minutes, they would bypass RCD completely. So, instead of challenging people, I would rather try to make them losing the motivation to cheat (by setting 1hp), hoping, that they learn, that cheating on your servers is only a short pleasure. I know that's no guarantee, but IMO it's a better way to go.

And if it gets too annoying, people can still ask /admin for help. One can also think about automatically adding a vote to ban a cheater, which would get approved automatically as soon as someone calls for that vote.

**Comment by black-roland** [comment]
> And that's a problem IMO. The IP test is strong and definite, while checking for name+clan is only kindergarden. If a guy is skilled enough to get a new ip, he'll soon comprehend that name+clan check, allowing to bypass it.

Most cheaters are stupid and do not know what the IP is. Many of them do not even try to change nickname (like "The Everest").

> Furthermore, if they realize, that they just have to disconnect and reconnect again, after playing for a few minutes, they would bypass RCD completely.

This can be a problem. I think need to store player's data always on leave, [not just when the warning level above the limit](https://github.com/chuck-norris-network/teeworlds/blob/809eca4a120bba682567545da571408f4bfed4ae/src/game/server/rcd.cpp#L97).

> So, instead of challenging people, I would rather try to make them losing the motivation to cheat (by setting 1hp), hoping, that they learn, that cheating on your servers is only a short pleasure.

I don't think it will help. This brings up many questions in chat like "WHY MY HP IS ALWAYS EQUAL 1???" and misunderstandings. Cheaters most likely start spamming, trolling, blocking and annoying other players.

In the current version you can check logs in any time and permanently ban the worst cheaters by /24 subnet.

> And if it gets too annoying, people can still ask /admin for help.

Unfortunately it wastes a lot of time. More easy justify banned by mistake later.

> One can also think about automatically adding a vote to ban a cheater, which would get approved automatically as soon as someone calls for that vote.

I thought about similar approach. We can start kick voting for detected cheaters. But many players do not know how to use the voting and do not track cheaters.

To be honest I do not even know how to make (code) this :)

**Comment by derselbst** [comment]
Ok then, for now I'd suggest we have a look on how RCD is doing "in production". Have you already set up all your servers (or just a few) using RCD? I'm really excited to see who gets banned and esp. who makes it back to the game. For the latter, I'll let you know ;)

> I think need to store player's data always on leave

I fear the memory usage that is linked to that. So lets better wait with that until it really gets necessary.

I'll think about other possible detection methods (fast aim, spinbots...) in the next couple of weeks. But I guess, the better RCD works, the lower is my motivation to actually implement them :D

**Comment by black-roland** [comment]
> Ok then, for now I'd suggest we have a look on how RCD is doing "in production". Have you already set up all your servers (or just a few) using RCD? I'm really excited to see who gets banned and esp. who makes it back to the game. For the latter, I'll let you know ;)

Yes, it works fine in production on all servers last few days. There is list of banned players (I do not want to publish full IP/names):

```
2016-09-26T11:36:53Z    © ∞dm ch        103.46.*.*
2016-09-26T11:38:58Z    © ctf ch        103.46.*.*
2016-09-26T18:41:54Z    © ∞dm ch        109.94.*.*
2016-09-26T18:50:06Z    © ctf ru        109.94.*.*
2016-09-27T12:54:47Z    © ctf ch        2.179.*.*
2016-09-27T12:55:15Z    © ctf ch        2.179.*.*
2016-09-27T13:13:48Z    © ctf ch        93.79.*.*
2016-09-27T20:24:33Z    © ctf ch        41.137.*.*
2016-09-27T21:53:57Z    © ctf ch        85.179.*.*
2016-09-27T23:26:38Z    © ctf ch        93.220.*.*
2016-09-28T12:23:35Z    © ctf ru        5.223.*.*
2016-09-28T12:35:09Z    © ctf ch        5.223.*.*
2016-09-28T15:41:55Z    © ctf ru        94.180.*.*
2016-09-29T10:18:35Z    © ctf ch        2.181.*.*
2016-09-29T15:29:51Z    © ctf ch        81.109.*.*
2016-09-30T08:58:19Z    © ctf ch        193.193.*.*
2016-09-30T08:58:19Z    © ctf ch        193.193.*.*
```

I blacklist (in DNSBL by /24) those who cheats many times.

There is RCD log (without names):

```
[rcd]: '(1)nameless tee' fires way too regularly
[rcd]: '(1)nameless tee' warnings: 1
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 5
[rcd]: '(1)nameless tee' fires way too regularly
[rcd]: '(1)nameless tee' warnings: 6
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 10
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 14
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 18
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 22
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 26
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 30
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 34
[rcd]: '(1)nameless tee' aimed exactly at '(2)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 38
[rcd]: '(1)nameless tee' fires way too regularly
[rcd]: '(1)nameless tee' warnings: 39
[rcd]: '(1)nameless tee' fires way too regularly
[rcd]: '(1)nameless tee' warnings: 40
[rcd]: '(1)nameless tee' warnings: 39 (30 sec without strange behavior)
[rcd]: '(1)nameless tee' aimed exactly at '(4)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 43
[rcd]: '(1)nameless tee' fires way too regularly
[rcd]: '(1)nameless tee' warnings: 44
[rcd]: '(1)nameless tee' aimed exactly at '(3)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 48
[rcd]: '(1)nameless tee' aimed exactly at '(4)nameless tee' position
[rcd]: '(1)nameless tee' warnings: 52
```

**Comment by black-roland** [comment]
> I fear the memory usage that is linked to that. So lets better wait with that until it really gets necessary.

I am not familiar with C++, but as I understand `std::map` size can be limited and do not eat a lot of memory.

> I'll think about other possible detection methods (fast aim, spinbots...) in the next couple of weeks. But I guess, the better RCD works, the lower is my motivation to actually implement them :D

Actually it works nice and smooth :)

What programming languages do you use?

**Comment by derselbst** [comment]
> Actually it works nice and smooth :)

Oh yeah, I just see ;)

> std::map size can be limited

Haven't heard of that, what are you refering to? `std::map::max_size()` is only a getter, if I'm not missing smth.?

> What programming languages do you use?

Though I'm only a student without THAT professional experience, I'm somewhat a C++ hardliner, esp. since the launch of C++11. C for most cases is way too low level IMO, thus you have to invent many things again and again. Java sucks for a couple of reasons, though C# is ok (that doesnt imply I like .NET ;) ).  [D](https://en.wikipedia.org/wiki/D_%28programming_language%29) looks interesting, haven't worked with it yet. I've worked with Python and found I dont like it (just as many other script languages).

**Comment by black-roland** [comment]
> Haven't heard of that, what are you refering to? std::map::max_size() is only a getter, if I'm not missing smth.?

Just checked specs. Yeah it is unlimited actually (limited only by OS/CPU).

**Comment by derselbst** [comment]
lets close that for now
